version: "3.4"
services:
 tdarr-node:
   container_name: tdarr-node
   image: ghcr.io/haveagitgat/tdarr_node:latest
   restart: unless-stopped
   #network_mode: service:tdarr
   environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - nodeName=a310
      - serverIP=192.168.32.175    #Your server IP Address
      - serverPort=30029
      - inContainer=true
      - ffmpegVersion=7
#      - NVIDIA_DRIVER_CAPABILITIES=all
#      - NVIDIA_VISIBLE_DEVICES=all

   volumes:
      - /home/ubuntu/tdarr/configs:/app/configs
      - /home/ubuntu/tdarr/logs:/app/logs
      - /mnt/media:/media
      - /mnt/tdarr:/temp

   devices:
      - /dev/dri:/dev/dri
