api:
  dashboard: true
  debug: true
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
  http-external:
    address: ":81"
  https-external:
    address: ":444"
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /config.yml
certificatesResolvers:
  cloudflare:
    acme:
      email: andy@expressittechtips.org #add your email
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        disablePropagationCheck: true 
        resolvers:
          - "1.1.1.1:53" #cloudflares dns
          - "1.0.0.1:53" #cloudflares dns